@startuml

title __COMPANY's Class Diagram__\n

  namespace com.company {
    class com.company.Country {
        - ISO_Code : String
        - name : String
        - peopleVaccinated : Long
        - peopleVaccinatedAsProportionOfWorld : Double
        - totalVaccinations : Long
        - totalVaccinationsAsProportionOfWorld : Double
        + getISO_Code()
        + getName()
        + getPeopleVaccinated()
        + getPeopleVaccinatedAsProportionOfWorld()
        + getTotalVaccinations()
        + getTotalVaccinationsAsProportionOfWorld()
        + setISO_Code()
        + setName()
        + setPeopleVaccinated()
        + setPeopleVaccinatedAsProportionOfWorld()
        + setTotalVaccinations()
        + setTotalVaccinationsAsProportionOfWorld()
    }
  }
  

  namespace com.company {
    class com.company.ReadJsonFile {
        {static} + nations : ArrayList<Country>
        {static} + worldData : World
        {static} + analyzeCountrySpecificData()
        {static} + analyzeWorldSpecificData()
        {static} + main()
        {static} + roundDecimalFormat3dp()
    }
  }
  

  namespace com.company {
    class com.company.World {
        - peopleVaccinated : Long
        - totalVaccinations : Long
        + getPeopleVaccinated()
        + getTotalVaccinations()
        + setPeopleVaccinated()
        + setTotalVaccinations()
    }
  }
  

  namespace com.company {
    class com.company.WriteJSONFile {
        {static} + vaccinationsData : JSONArray
        {static} + createJSONObjectFromNationsData()
        {static} + writeFile()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
